version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: abubaska/devops-for-programmers-project-74
    volumes:
      - "./app:/app"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    command: bash -c 'sleep 5 && npm test'
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  app:
    driver: bridge
